# Generated by Django 2.0.1 on 2018-04-01 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oslapp', '0002_auto_20180401_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='oslapp.Profile'),
        ),
    ]
