# Generated by Django 2.0.1 on 2018-04-01 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oslapp', '0003_document_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='username',
        ),
    ]
