# Generated by Django 2.0.1 on 2018-04-14 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oslapp', '0009_auto_20180414_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dp',
            field=models.FileField(null=True, upload_to='user/'),
        ),
    ]
