# Generated by Django 2.0.1 on 2018-04-14 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oslapp', '0010_profile_dp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='dp',
        ),
    ]
