# Generated by Django 2.0.1 on 2018-04-17 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oslapp', '0015_auto_20180416_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='follows',
        ),
        migrations.AddField(
            model_name='profile',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
